# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_apk_system_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('systemSize', models.CharField(max_length=11)),
                ('fixedSize', models.CharField(max_length=11)),
                ('surplusSize', models.CharField(max_length=11)),
                ('hdversion', models.CharField(max_length=40)),
            ],
        ),
    ]
